name: Build LaTeX document

on:
  push:
    # Run on pushes to the main branch…
    branches:
      - main
    # …and also on pushes of version tags like v1.2.3
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build_latex:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          latexmk_shell_escape: true
          extra_system_packages: inkscape

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: main.pdf

      - name: Create / Update versioned release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          files: main.pdf

      - name: Create / Update “latest” release
        if: github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v2
        with:
          # this tag will always point at the tip of main
          tag_name: latest
          name: Latest
          files: main.pdf
